CREATE TABLE lkup_states(
    state_id VARCHAR(2) PRIMARY KEY,
    state_name VARCHAR(20)
);

INSERT INTO lkup_states (state_id, state_name) VALUES ('AL', 'Alabama');
INSERT INTO lkup_states (state_id, state_name) VALUES ('AK', 'Alaska');
INSERT INTO lkup_states (state_id, state_name) VALUES ('AZ', 'Arizona');
INSERT INTO lkup_states (state_id, state_name) VALUES ('AR', 'Arkansas');
INSERT INTO lkup_states (state_id, state_name) VALUES ('CA', 'California');
INSERT INTO lkup_states (state_id, state_name) VALUES ('CO', 'Colorado');
INSERT INTO lkup_states (state_id, state_name) VALUES ('CT', 'Connecticut');
INSERT INTO lkup_states (state_id, state_name) VALUES ('DE', 'Delaware');
INSERT INTO lkup_states (state_id, state_name) VALUES ('FL', 'Florida');
INSERT INTO lkup_states (state_id, state_name) VALUES ('GA', 'Georgia');
INSERT INTO lkup_states (state_id, state_name) VALUES ('HI', 'Hawaii');
INSERT INTO lkup_states (state_id, state_name) VALUES ('ID', 'Idaho');
INSERT INTO lkup_states (state_id, state_name) VALUES ('IL', 'Illinois');
INSERT INTO lkup_states (state_id, state_name) VALUES ('IN', 'Indiana');
INSERT INTO lkup_states (state_id, state_name) VALUES ('IA', 'Iowa');
INSERT INTO lkup_states (state_id, state_name) VALUES ('KS', 'Kansas');
INSERT INTO lkup_states (state_id, state_name) VALUES ('KY', 'Kentucky');
INSERT INTO lkup_states (state_id, state_name) VALUES ('LA', 'Louisiana');
INSERT INTO lkup_states (state_id, state_name) VALUES ('ME', 'Maine');
INSERT INTO lkup_states (state_id, state_name) VALUES ('MD', 'Maryland');
INSERT INTO lkup_states (state_id, state_name) VALUES ('MA', 'Massachusetts');
INSERT INTO lkup_states (state_id, state_name) VALUES ('MI', 'Michigan');
INSERT INTO lkup_states (state_id, state_name) VALUES ('MN', 'Minnesota');
INSERT INTO lkup_states (state_id, state_name) VALUES ('MS', 'Mississippi');
INSERT INTO lkup_states (state_id, state_name) VALUES ('MO', 'Missouri');
INSERT INTO lkup_states (state_id, state_name) VALUES ('MT', 'Montana');
INSERT INTO lkup_states (state_id, state_name) VALUES ('NE', 'Nebraska');
INSERT INTO lkup_states (state_id, state_name) VALUES ('NV', 'Nevada');
INSERT INTO lkup_states (state_id, state_name) VALUES ('NH', 'New Hampshire');;
INSERT INTO lkup_states (state_id, state_name) VALUES ('NJ', 'New Jersey');
INSERT INTO lkup_states (state_id, state_name) VALUES ('NM', 'New Mexico');
INSERT INTO lkup_states (state_id, state_name) VALUES ('NY', 'New York');
INSERT INTO lkup_states (state_id, state_name) VALUES ('NC', 'North Carolina');
INSERT INTO lkup_states (state_id, state_name) VALUES ('ND', 'North Dakota');
INSERT INTO lkup_states (state_id, state_name) VALUES ('OH', 'Ohio');
INSERT INTO lkup_states (state_id, state_name) VALUES ('OK', 'Oklahoma');
INSERT INTO lkup_states (state_id, state_name) VALUES ('OR', 'Oregon');
INSERT INTO lkup_states (state_id, state_name) VALUES ('PA', 'Pennsylvania');
INSERT INTO lkup_states (state_id, state_name) VALUES ('RI', 'Rhode Island');
INSERT INTO lkup_states (state_id, state_name) VALUES ('SC', 'South Carolina');
INSERT INTO lkup_states (state_id, state_name) VALUES ('SD', 'South Dakota');
INSERT INTO lkup_states (state_id, state_name) VALUES ('TN', 'Tennessee');
INSERT INTO lkup_states (state_id, state_name) VALUES ('TX', 'Texas');
INSERT INTO lkup_states (state_id, state_name) VALUES ('UT', 'Utah');
INSERT INTO lkup_states (state_id, state_name) VALUES ('VT', 'Vermont');
INSERT INTO lkup_states (state_id, state_name) VALUES ('VA', 'Virginia');
INSERT INTO lkup_states (state_id, state_name) VALUES ('WA', 'Washington');
INSERT INTO lkup_states (state_id, state_name) VALUES ('WV', 'West Virginia');
INSERT INTO lkup_states (state_id, state_name) VALUES ('WI', 'Wisconsin');
INSERT INTO lkup_states (state_id, state_name) VALUES ('WY', 'Wyoming');
