CREATE TABLE product (
    prod_id SERIAL PRIMARY KEY,
    prod_brand_id INTEGER,
    prod_category_id INTEGER,
    prod_name VARCHAR(50),
    prod_desc TEXT,
    prod_size VARCHAR(25),
    prod_price FLOAT,
    prod_image text
);

--rubs
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (2, 3, 'Bacon BBQ Rub', 'Introducing our 7th wonder of the world - Bacon BBQ! There is nothing like it in the BBQ market today.  What is this good on? Everything, duh. Bacon makes everything better! This is an all purpose bbq rub so it truly is good on everything. In fact, it is so good, that meat is optional! Just lick your finger and give it a shot plain. Trust us!', '14 oz shaker', '9', 'https://cdn.shopify.com/s/files/1/0391/9501/products/image_e05db324-3f0f-4dc0-80cb-a882a0c5544b_1024x1024.jpg?v=1533178599');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (1, 3, 'Traeger Beef Rub', 'Beef up your BBQ routine with our Beef Rub. Featuring brown sugar and chili pepper, it pairs perfectly with our Sweet & Heat sauce.', '8.25 oz', '9.99', 'https://www.traegergrills.com/images/en-us/pdp/Beef-Rub-Main-Traeger-Wood-Pellet-Grills.png?w=390');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (1, 3, 'Traeger Chicken Rub', 'Here is the rub down. Slap it on to make every bird bold, juicy, and oh so succulent', '8.25 oz', '9.99', 'https://www.traegergrills.com/images/en-us/pdp/Chicken-Rub-Main-Traeger-Wood-Pellet-Grills.png?w=390');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (2, 3, 'Deez Nuts Honey Pecan BBQ Rub', 'We have heard your request and answered the call. This rub started from our popular Honey Hog BBQ rub. We experimented and had several top chefs cook with different levels of pecan flavoring. We have finally perfected what we think is the best pecan rub on the market!  This sweet rub is excellent on pork, poultry and fish!. You can apply it to anything you like and the color is amazing. ', '14 oz shaker', '9', 'https://cdn.shopify.com/s/files/1/0391/9501/products/image_dab028ec-996d-47a9-a7b9-e6979bc6177b_1024x1024.jpg?v=1533178546');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (2, 3, 'Holy Cow BBQ Rub', 'This BBQ rub screams Texas! If you have been to Franklin, Kreuz, Blacks or Smittys then you know what I am talking about. This beefy BBQ seasoning is fantastic on brisket, tri-tip and steaks, but can be applied to anything you like. Many folks love it on chicken and burgers.', '14 oz shaker', '9', 'https://cdn.shopify.com/s/files/1/0391/9501/products/image_c59c02df-e3fd-483c-b48a-e109263a476d_1024x1024.jpg?v=1533178449');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (2, 3, 'The Holy Gospel BBQ Rub', 'The Holy Gospel BBQ Rub. A mashup of our popular Holy Cow beef seasoning and The Gospel All Purpose rub. NO, it is not 50-50. This took tons of test cooks to get it right. We saw plenty of folks mashing two rubs together plus acted on customer feedback of Holy Cow being too much of a black pepper punch or Gospel needing a little more. Whatever the case, this blend is great on ribs, chicken and beef!', '14 oz shaker', '9', 'https://cdn.shopify.com/s/files/1/0391/9501/products/image_3104d122-4471-446f-bdea-20fd6ded2ada_1024x1024.jpg?v=1533178330');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (2, 3, 'Honey Bacon BBQ Rub', 'We have taken our super popular Honey Hog rub and add BACON, because Bacon makes everything taste better!!!! This may be our best tasting rub straight out of the bottle. Of course this comes with more of our signature unique and funny BBQ art on the front of the bottle. ', '14 oz shaker', '9', 'https://cdn.shopify.com/s/files/1/0391/9501/products/Honey_Bacon_bottle_insta_1024x1024.jpg?v=1535368885');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (2, 3, 'Honey Hog HOT BBQ Rub', 'This rub is an offshoot of our popular Honey Hog with Jalapeño added. This sweet\heat rub is excellent on pork ribs, pulled pork, poultry and fish. Combine it with Honey Hog BBQ and you have a lethal combo for ribs that is making waves all over the competition circuit. It is also fantastic on chicken wings and cooks down to not be as hot as when eaten plain.', '14 oz shaker', '9', 'https://cdn.shopify.com/s/files/1/0391/9501/products/image_23697619-407a-4307-a03c-7547e76ed032_1024x1024.jpg?v=1533178514');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (2, 3, 'Honey Hog BBQ Rub', 'This BBQ rub comes from our southern upbringing. This sweet rub is excellent on pork ribs, pulled pork, poultry and vegetables. You can apply it to anything you like and the color is amazing. Check out the picture below!', '14 oz shaker', '9', 'https://cdn.shopify.com/s/files/1/0391/9501/products/image_a2188099-c285-42ac-9e5b-3fa3a408d65b_1024x1024.jpg?v=1533178478');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (7, 3, 'Killer Hogs The A.P. Rub', 'This is our "All Purpose" Seasoning.  If you are serious about grilling and smoking, you need a flavorful and balanced seasoning versatile enough to be used on everything.  The A.P. Rub works on pork, beef, chicken... even veggies.  Use it alone and keep it simple – or use it in combination with other Killer Hogs Rubs for even bigger flavor.', '12 oz shaker', '9.97', 'https://cdn.shopify.com/s/files/1/1190/2102/products/APF_1024x1024.jpg?v=1508511841');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (7, 3, 'Killer Hogs Steak & Chop Rub', 'Created specifically for open-flame grilling and smoking Steaks and Chops, this seasoning is flavorful blend of salt, pepper, herbs and spices.  If you want authentic steak house flavor, The Steak Rub is all you need.  Apply to the outside of all your steaks, chops - even chicken - before grilling or smoking.', '6.2 oz shaker', '6.97', 'https://cdn.shopify.com/s/files/1/1190/2102/products/SteakF_1024x1024.jpg?v=1508511767');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (4, 3, 'Oakridge BBQ Black Ops Brisket Rub', '', '6 oz bag', '7.95', 'https://www.atbbq.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/o/a/oakridge-bbq-black-ops-brisket-rub-6-oz.jpg');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (4, 3, 'Oakridge BBQ Santa Maria Seasoning', '', '5 oz bag', '8.5', 'https://www.atbbq.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/o/a/oakridge-bbq-santa-maria-grill-seasoning-5-oz.jpg');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (5, 3, 'Plowboys Bovine Bold Rub', '', '12 oz shaker', '8.99', 'https://www.atbbq.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/p/l/plowboys-bovine-bold-rub-12oz-01.jpg');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (5, 3, 'Plowboys Yardbird Rub', '', '12 oz shaker', '8.99', 'https://www.atbbq.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/p/l/plowboys-yardbird-rub-14oz-01.jpg');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (1, 3, 'Traeger Pork & Poultry Rub', 'Apple and honey flavor join forces to guarantee your chicken and pork creations are damn delicious.', '8.25 oz', '9.99', 'https://www.traegergrills.com/images/en-us/pdp/Pork-Poultry-Rub-Main-Traeger-Wood-Pellet-Grills.png?w=390');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (1, 3, 'Traeger Prime Rib Rub', 'We have got beef with boring BBQ. Hit your prime rib, or other beef cuts, with this seasoning packed with garlic, herbs, and addictive flavor.', '8.25 oz', '9.99', 'https://www.traegergrills.com/images/en-us/pdp/Prime-Rib-Rub-Main-Traeger-Wood-Pellet-Grills.png?w=390');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (2, 3, 'The Gospel All Purpose BBQ Rub', 'What if you could only buy one rub? This All-Purpose BBQ seasoning can be described as the one rub you need for every cook; beef, chicken, pork, seafood vegetables and more! This southwestern style rub has a bright red color and killer BBQ flavor.', '14 oz shaker', '9', 'https://cdn.shopify.com/s/files/1/0391/9501/products/image_4945b7db-10c9-457d-9159-8f2455e26a21_1024x1024.jpg?v=1533178417');

--sauces
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (6, 4, 'Blues Hog Honey Mustard Sauce', 'Blues Hog Honey Mustard is a thick golden gourmet sauce with the sweet taste of honey combined with the zesty taste of prepared mustard with an exotic blend of spices to nurture the flavors. Excellent for use as a dipping sauce, a basting sauce, we have even used it as a delicious salad dressing!', '16 oz', '6.95', 'https://www.atbbq.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/m/img_9761-edit_1.jpg');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (6, 4, 'Blues Hog Original BBQ Sauce', 'Blues Hog Original BBQ Sauce is a gourmet sauce made from all natural ingredients, and its sweet, yet spicy, flavor enhances the taste of all meats prepared on the grill or in the kitchen.', '16 oz', '5.95', 'https://www.atbbq.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/m/img_9752-edit.jpg');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (6, 4, 'Blues Hog Smokey Mountain BBQ Sauce', 'The newest sauce from Blues Hog, this Smokey Mountain Sauce provides a sweet, balanced flavor that will complement any blue ribbon BBQ.', '16 oz', '5.95', 'https://www.atbbq.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/m/img_9758-edit.jpg');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (6, 4, 'Blues Hog Tennessee Red BBQ Sauce', 'Blues Hog Tennessee Red Sauce is a vinegar/pepper based sauce that can be found in "Barbecue Joints" down in the South. Excellent on pork and beef sandwiches it can be used as a marinade for chicken or wild game, used as a mopping sauce on the grill, or we have even used it in our Dirty Rice and Baked Bean recipes. It gives foods a unique boost of flavor with a "zesty attitude."', '16 oz', '5.95', 'https://www.atbbq.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/m/img_9755-edit.jpg');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (7, 4, 'Killer Hogs Vinegar Sauce', 'First Place Vinegar Sauce 2016 Memphis In May BBQ World Championships. When a mediocre sauce just won’t cut it, this sauce here will deliver that world champion level of flavor your BBQ deserves.  Inspired by our roots in West Tennessee barbecue, The Vinegar Sauce is sweet and tangy with perfectly balanced flavors and a kick of heat at the end.', '18 oz', '5.97', 'https://cdn.shopify.com/s/files/1/1190/2102/products/VinSauceF_1024x1024.jpg?v=1508512442');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (3, 4, 'Meat Mitch WHOMP! Naked BBQ Sauce', 'Meat Mitch WHOMP! Naked BBQ Sauce HFCS (High-Fructose Corn Syrup)-Free and Gluten-Free All Natural Competition BBQ Sauce SO GOOD, IT WILL MAKE YOU SQUEAL! SHE IS SWEET WITH HEAT, PODS! When in doubt, JUST GET NAKED! Use it for ribs, steak, brisket, pork, foie gras, chicken, 9 irons, eggs, scrapple, your mother-in-law, use it to water flowers. WHOMP! NO FRUCTOSE CORN SYRUP At Meat Mitch we do not judge, we get judged, and experts love this All-Natural Q sauce made for Championship BBQ competitions. This unique sauce is stripped down to natural, raw ingredients. NO HI-FRUCTOSE CORN SYRUP, NO FISH in this dish, & do not expect some late night Glute-y Call. It is also GLUTEN FREE. This sauce is so Naked it might go streaking thru the Quad...', '21 oz', '6.99', 'https://cdn.shopify.com/s/files/1/1753/4835/products/naked-jar-21oz_204df68a-bf62-43e8-8f16-580083edf3e0_1200x.jpg?v=1489086795');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (3, 4, 'Meat Mitch Whomp! BBQ Sauce', 'Meat Mitch Competition WHOMP! BBQ Sauce GLUTEN FREE SO GOOD, IT WILL MAKE YOU SQUEAL! SHE IS SWEET WITH HEAT, PODS! When in doubt, JUST ADD SAUCE! Use it for ribs, steak, brisket, pork, foie gras, chicken, 9 irons, eggs, chili, your mother-in-law, use it to water flowers.', '21 oz', '6.99', 'https://cdn.shopify.com/s/files/1/1753/4835/products/Whomp-jar-21oz_1200x.jpg?v=1489086561');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (1, 4, 'Traeger Apricot Sauce', 'Our most popular sauce is back and better than ever. It is tangy and sweet, with a little kick, and ready to meet your meatloaf, pork or chicken', '16 oz', '9.99', 'https://www.traegergrills.com/images/DevAssets/Products/Rubs/SAU028_NA_1.png?w=390');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (1, 4, 'Traeger Signature Sauce', 'Our Signature BBQ Sauce features a combination of sweet and savory flavors that go great on beef, pork, and chicken. Brush it on or leave on the side for dipping—your guests will thank you.', '16 oz', '9.99', 'https://www.traegergrills.com/images/DevAssets/Products/Rubs/SAU033_NA_1.png?w=390');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (1, 4, 'Traeger Sweet Heat', 'The name says it all—sweet molasses and apricot unite with peppery heat for a dream team of flavor. Slather it on a pork loin while you roast it to perfection on the Traeger.', '16 oz', '9.99', 'https://www.traegergrills.com/images/DevAssets/Products/Rubs/SAU026_NA_1.png?w=390');
INSERT INTO product (prod_brand_id, prod_category_id, prod_name, prod_desc, prod_size, prod_price,prod_image) VALUES (1, 4, 'Traeger Texas Spicy BBQ', 'Kickass wings are a bottle of Texas Spicy BBQ Sauce away. Douse everything from game day wings, to a pulled pork sandwich.', '16 oz', '9.99', 'https://www.traegergrills.com/images/DevAssets/Products/Rubs/SAU029_NA_1.png?w=390');